-- Criação das tabelas para o sistema de vendas

-- Criação das sequências para geração de IDs
CREATE SEQUENCE IF NOT EXISTS produtos_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS clientes_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS formas_pagamento_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS vendas_seq START WITH 1 INCREMENT BY 1;

-- Tabela de produtos
CREATE TABLE IF NOT EXISTS produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto VARCHAR(10) NOT NULL UNIQUE,
    produto VARCHAR(255) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    pedido_minimo INTEGER,
    custo_unitario DECIMAL(10,2),
    preco_sugerido DECIMAL(10,2),
    cento_preco DECIMAL(10,2),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- Tabela de clientes
CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente VARCHAR(10) NOT NULL UNIQUE,
    nome_cliente VARCHAR(255) NOT NULL,
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    tipo_cliente VARCHAR(20) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- Tabela de formas de pagamento
CREATE TABLE IF NOT EXISTS formas_pagamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pagamento VARCHAR(10) NOT NULL UNIQUE,
    forma_pagamento VARCHAR(50) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- Tabela de vendas
CREATE TABLE IF NOT EXISTS vendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda VARCHAR(10) NOT NULL UNIQUE,
    data DATE NOT NULL,
    produto_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    preco_unitario DECIMAL(10,2) NOT NULL,
    receita_total DECIMAL(10,2) NOT NULL,
    cliente_id BIGINT NOT NULL,
    forma_pagamento_id BIGINT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (produto_id) REFERENCES produtos(id),
    FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    FOREIGN KEY (forma_pagamento_id) REFERENCES formas_pagamento(id)
);

-- Índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_produtos_categoria ON produtos(categoria);
CREATE INDEX IF NOT EXISTS idx_produtos_id_produto ON produtos(id_produto);
CREATE INDEX IF NOT EXISTS idx_clientes_cidade ON clientes(cidade);
CREATE INDEX IF NOT EXISTS idx_clientes_tipo ON clientes(tipo_cliente);
CREATE INDEX IF NOT EXISTS idx_clientes_id_cliente ON clientes(id_cliente);
CREATE INDEX IF NOT EXISTS idx_vendas_data ON vendas(data);
CREATE INDEX IF NOT EXISTS idx_vendas_cliente ON vendas(cliente_id);
CREATE INDEX IF NOT EXISTS idx_vendas_produto ON vendas(produto_id);
CREATE INDEX IF NOT EXISTS idx_vendas_id_venda ON vendas(id_venda);
