-- Inserção dos dados de produtos
-- V3__Insert_Produtos.sql

INSERT INTO produtos (id_produto, produto, categoria, pedido_minimo, custo_unitario, preco_sugerido, cento_preco, is_active, created_at, updated_at) VALUES
('P001', 'Coxinha de Frango', 'Salgado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P002', 'Bolinha de queijo', 'Salgado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P003', 'Kibe', 'Salgado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P004', 'Croquete de carne', 'Salgado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P005', 'Risole de Carne', 'Salgado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P006', 'Risole de Calabresa', 'Salgado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P007', 'Risole de Pizza', 'Salgado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P008', 'Risole de Queijo com Parmesão', 'Salgado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P009', 'Risole de Brócolis com Ricota', 'Salgado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P010', 'Esfiha de Carne', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P011', 'Esfiha de Calabresa', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P012', 'Esfiha de Frango com requeijão', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P013', 'Esfiha de queijo com Parmesão', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P014', 'Esfiha de Brócolis com Ricota', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P015', 'Pastelzinho de Carne', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P016', 'Pastelzinho de Calabresa', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P017', 'Pastelzinho de Frango com requeijão', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P018', 'Pastelzinho de Queijo com Parmesão', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P019', 'Pastelzinho de Brócolis com Ricota', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P020', 'Enroladinho de Salsicha', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P021', 'Enroladinho de Pizza', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P022', 'Empada de Palmito', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P023', 'Empada de Frango', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P024', 'Empada de Queijo', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P025', 'Empada de Calabresa com Requeijão', 'Assado', 25, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P026', 'Kibe de Soja', 'Vegetariano', 25, NULL, 0.70, 70.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P027', 'Croquete de cenoura', 'Vegetariano', 25, NULL, 0.70, 70.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P028', 'Croquete de Milho', 'Vegetariano', 25, NULL, 0.70, 70.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P029', 'Risole de Brócolis', 'Vegetariano', 25, NULL, 0.70, 70.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P030', 'Risole de Escarola', 'Vegetariano', 25, NULL, 0.70, 70.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P031', 'Risole de Palmito', 'Vegetariano', 25, NULL, 0.70, 70.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P032', 'Risole de Carne de Soja', 'Vegetariano', 25, NULL, 0.70, 70.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P033', 'Esfiha de Brócolis', 'Vegetariano', 25, NULL, 0.70, 70.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P034', 'Esfiha de Escarola', 'Vegetariano', 25, NULL, 0.70, 70.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P035', 'Esfina de Carne de Soja', 'Vegetariano', 25, NULL, 0.70, 70.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P036', 'Empada de Palmito', 'Vegetariano', 25, NULL, 0.70, 70.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P037', 'Croquete de Bacalhau', 'Salgados Especiais', 50, NULL, 1.15, 115.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P038', 'Croquete de Carne Seca', 'Salgados Especiais', 50, NULL, 1.15, 115.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P039', 'Bolinho de Bacon com catupiry', 'Salgados Especiais', 50, NULL, 1.20, 120.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P040', 'Coxinha de Costela', 'Salgados Especiais', 50, NULL, 1.20, 120.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P041', 'Coxinha de Frango com catupiry', 'Salgados Especiais', 50, NULL, 0.95, 95.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P042', 'Esfiha de Carne Seca com catupiry', 'Salgados Especiais', 50, NULL, 1.20, 120.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P043', 'Empada de Camarão', 'Salgados Especiais', 50, NULL, 1.10, 110.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P044', 'Coxinha de Jaca', 'Vegetariano Especiais', 50, NULL, 1.10, 110.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P045', 'Risole de Shimeji', 'Vegetariano Especiais', 50, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P046', 'Esfiha de Shimeji', 'Vegetariano Especiais', 50, NULL, 0.80, 80.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P047', 'Esfiha de Jaca', 'Vegetariano Especiais', 50, NULL, 1.10, 110.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P048', 'Frango (patê de frango com cenoura e alface)', 'Lanchinhos', 50, NULL, 1.30, 130.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P049', 'Queijo e Presunto (Queijo mussarela, presunto, alface, tomate e maionese)', 'Lanchinhos', 50, NULL, 1.30, 130.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P050', 'Salame (Salame, queijo prato, alface, tomate e maionese)', 'Lanchinhos', 50, NULL, 1.30, 130.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P051', 'Atum (Patê de atum e alface)', 'Lanchinhos', 50, NULL, 1.15, 115.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P052', 'Ervas finas com alho (patê de ervas finas com alho e tomate)', 'Lanchinhos Vegetariano', 50, NULL, 1.15, 115.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P053', 'Azeitona preta (patê de azeitona preta, alface e tomate)', 'Lanchinhos Vegetariano', 50, NULL, 1.15, 115.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P054', 'Pasta de berinjela (pasta de berinjela, alface e tomate)', 'Lanchinhos Vegetariano', 50, NULL, 1.15, 115.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P055', 'Chocolate tradicional', 'Brigadeiros - tradicional', 50, NULL, 1.00, 100.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P056', 'Beijinho', 'Brigadeiros - tradicional', 50, NULL, 1.00, 100.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P057', 'Bicho de pé', 'Brigadeiros - tradicional', 50, NULL, 1.00, 100.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P058', 'Brigadeiro Branco', 'Brigadeiros - tradicional', 50, NULL, 1.00, 100.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P059', 'Prestígio', 'Brigadeiros - tradicional', 50, NULL, 1.00, 100.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P060', 'Cajuzinho', 'Brigadeiros - tradicional', 50, NULL, 1.00, 100.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P061', 'Romeu e Julieta', 'Brigadeiros - tradicional', 50, NULL, 1.00, 100.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P062', 'Paçoca', 'Brigadeiros - tradicional', 50, NULL, 1.00, 100.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P063', 'Olho de Sogra', 'Brigadeiros - tradicional', 50, NULL, 1.00, 100.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P064', 'Ninho com nutella', 'Brigadeiros - Gourmet', 50, NULL, 1.40, 140.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P065', 'Churros com doce de leite', 'Brigadeiros - Gourmet', 50, NULL, 1.40, 140.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P066', 'Brigadeiro com nutella', 'Brigadeiros - Gourmet', 50, NULL, 1.40, 140.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P067', 'Brigadeiro de limão com suspiro', 'Brigadeiros - Gourmet', 50, NULL, 1.40, 140.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P068', 'Ferrero', 'Brigadeiros - Gourmet', 50, NULL, 1.40, 140.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P069', 'Surpresa de Uva (Brigadeiro de ninho e uva thompson)', 'Doce no copinho', 50, NULL, 1.20, 120.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P070', 'Chocolate com morango (brigadeiro tradicional e morangos)', 'Doce no copinho', 50, NULL, 1.20, 120.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P071', 'Bicho de pé (brigadeiro de morango e morango)', 'Doce no copinho', 50, NULL, 1.20, 120.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P072', 'Mousse de limão (mousse de limão com raspas de limão)', 'Doce no copinho', 50, NULL, 1.20, 120.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P073', 'Brigadeiro', 'Mini Brownies', 50, NULL, 1.20, 120.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P074', 'Nutella', 'Mini Brownies', 50, NULL, 1.20, 120.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P075', 'Leite Ninho', 'Mini Brownies', 50, NULL, 1.20, 120.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P076', 'Doce de leite', 'Mini Brownies', 50, NULL, 1.20, 120.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P077', 'Abacaxi com coco', 'Empadinha Doce', 50, NULL, 1.00, 100.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P078', 'Brigadeiro', 'Palha Italiana', 50, NULL, 1.00, 100.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('P079', 'Leite Ninho', 'Palha Italiana', 50, NULL, 1.00, 100.00, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
