-- Inserção dos dados de clientes
-- V4__Insert_Clientes.sql

INSERT INTO clientes (id_cliente, nome_cliente, bairro, cidade, tipo_cliente, is_active, created_at, updated_at) VALUES
('C001', 'Maria Souza', 'Centro', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C002', 'João Pereira', 'Vila Nova', 'Suzano', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C003', 'Ana Lima', 'Jardim Brasil', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C004', 'Carlos Silva', 'Centro', 'Poá', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C005', 'Fernanda Reis', 'Bela Vista', 'Guararema', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C006', 'Lucas Andrade', 'Santa Clara', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C007', 'Mariana Costa', 'Jardim América', 'Arujá', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C008', 'Pedro Oliveira', 'Vila Nova', 'Suzano', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C009', 'Juliana Martins', 'Bela Vista', 'Itaquaquecetuba', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C010', 'Rafael Almeida', 'Vila Esperança', 'Ferraz de Vasconcelos', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C011', 'Camila Ferreira', 'Centro', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C012', 'André Rocha', 'Jardim Brasil', 'Guararema', 'Pessoa Jurídica', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C013', 'Patrícia Gomes', 'Vila Nova', 'Poá', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C014', 'Felipe Souza', 'Bela Vista', 'Suzano', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C015', 'Bianca Mendes', 'Santa Clara', 'Itaquaquecetuba', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C016', 'Rodrigo Carvalho', 'Jardim América', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C017', 'Larissa Ribeiro', 'Centro', 'Arujá', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C018', 'Daniel Moreira', 'Vila Esperança', 'Suzano', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C019', 'Fernanda Alves', 'Jardim Brasil', 'Ferraz de Vasconcelos', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C020', 'Bruno Lima', 'Bela Vista', 'Guararema', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C021', 'Ana Luiza', 'Centro', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C022', 'Marcelo Brito', 'Vila Hélio', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C023', 'Pedro Henrique', 'Jardim Avenida', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C024', 'Mariana Alves', 'Jardim Veneza', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C026', 'Eduardo Santana', 'Vila Natal', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C027', 'João Vitor', 'Vila Bela Vista', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C028', 'Patrícia Gomes', 'Mogi Moderno', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C029', 'Camila Rocha', 'Alto da Boa Vista', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C030', 'Rodrigo Pires', 'Parque Santana', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C031', 'Lucas Gabriel', 'Centro', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C032', 'Vanessa Barbosa', 'Centro', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C033', 'Isabela Martins', 'Vila Natal', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C034', 'Felipe Duarte', 'Alto da Boa Vista', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C035', 'Rafael Souza', 'Vila Natal', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C036', 'Aline Castro', 'Vila Sud Menuci', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C037', 'Fernanda Lima', 'Centro', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C038', 'Bruno Araújo', 'Jardim Veneza', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C039', 'Guilherme Torres', 'Centro', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C040', 'Gabriela Nunes', 'Mogi Moderno', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C041', 'Beatriz Mendes', 'Jardim Veneza', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C042', 'Leonardo Almeida', 'Vila Natal', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C043', 'Thiago Carvalho', 'Parque Santana', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C044', 'Sofia Moreira', 'Centro', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C045', 'Larissa Costa', 'Parque Santana', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C046', 'Diego Fernandes', 'Alto da Boa Vista', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C047', 'André Luiz', 'Centro', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C048', 'Carolina Ribeiro', 'Centro', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C049', 'Juliana Oliveira', 'Mogi Moderno', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C050', 'Matheus Silva', 'Centro', 'Mogi das Cruzes', 'Pessoa Física', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
